"""Scoreboard tests."""
import json as jsonxx
from .base import PickemTestCase

class ScoreboardTestCase(PickemTestCase):
    """Tests for Scoreboard routes."""
    def test_scoreboard(self):
        """Does the Scoreboard load?"""
        with self.app.test_client() as http:
            self.login_user(http)
            resp = http.get("/scoreboard")
            html = resp.get_data(as_text=True)
            self.assertEqual(resp.status_code, 200)
            self.assert_routed_to_scoreboard(html)

    def test_scoreboard_as_anon(self):
        """Is the Scoreboard blocked when not logged in?"""
        self.is_get_route_as_anon_blocked("/scoreboard")

    def test_scoreboard_full_update(self):
        """Does scoreboard full update route allow admin access? (API call skipped in testing)"""
        with self.app.test_client() as http:
            self.login_user(http) # Logs in as admin
            resp = http.get("/scoreboard/update", follow_redirects=True)
            html = resp.get_data(as_text=True)
            self.assertEqual(resp.status_code, 200)
            self.assert_routed_to_scoreboard(html)

    def test_scoreboard_full_update_as_nonadmin_user(self):
        """Does scoreboard full update route block non-admin users?"""
        with self.app.test_client() as http:
            self.is_admin_get_route_as_user_blocked("/scoreboard/update")

    def test_scoreboard_full_update_as_anon(self):
        """Is the scoreboard full update blocked when not logged in?"""
        with self.app.test_client() as http:
            self.is_get_route_as_anon_blocked("/scoreboard/update")

    def test_scoreboard_games_api(self):
        """Are a collection of games with scores returned as JSON?"""
        with self.app.test_client() as http:
            self.login_user(http)
            resp = http.get("/scoreboard/games/2025-04-30")
            json = resp.get_json()
            self.assertEqual(resp.status_code, 200)

            # Update game IDs in the expected response
            fixed_april30_scores = self.EXPECTED_RESPONSE_APRIL_30
            for game in fixed_april30_scores["games"]:
                game["id"] += self.april30_first_game_id

            self.assertDictEqual(json, fixed_april30_scores)

    def test_scoreboard_games_api_not_a_game_day(self):
        """Is JSON returned for a day with no games?"""
        with self.app.test_client() as http:
            self.login_user(http)
            resp = http.get("/scoreboard/games/2025-01-02")
            json = resp.get_json()
            self.assertEqual(resp.status_code, 200)
            self.assertDictEqual(json, self.EXPECTED_RESPONSE_JAN_2)

    EXPECTED_RESPONSE_JAN_2 = {
        "day": "2025-01-02",
        "dayDisplay": "Thu, January 2",
        "prevDay": "2025-01-01",
        "nextDay": "2025-01-03",
        "userPoints": 0,
        "games": []
    }

    @property
    def EXPECTED_RESPONSE_APRIL_30(self):
        return {
        "day": "2025-04-30",
        "dayDisplay": "Wed, April 30",
        "nextDay": "2025-05-01",
        "prevDay": "2025-04-29",
        "userPoints": 1,
        "games": [
            {
                "apiID": 401769679,
                "awayTeam": {
                    "abbreviation": "STL",
                    "apiID": 24,
                    "errors": 0,
                    "hits": 7,
                    "id": 26,
                    "leagueID": 1,
                    "location": "St. Louis",
                    "logoURL": "https://a.espncdn.com/i/teamlogos/mlb/500/stl.png",
                    "name": "Cardinals",
                    "score": 6,
                },
                "homeTeam": {
                    "abbreviation": "CIN",
                    "apiID": 17,
                    "errors": 0,
                    "hits": 3,
                    "id": 8,
                    "leagueID": 1,
                    "location": "Cincinnati",
                    "logoURL": "https://a.espncdn.com/i/teamlogos/mlb/500/cin.png",
                    "name": "Reds",
                    "score": 0,
                },
                "id": 0,
                "pick": None,
                "startTime": "2025-04-30T09:40:00-07:00",
                "status": "Final",
                "statusDetail": "Final",
                "subseasonID": 1,
                "winTeamID": 26,
            },
            {
                "apiID": 401695360,
                "awayTeam": {
                    "abbreviation": "DET",
                    "apiID": 6,
                    "errors": 1,
                    "hits": 11,
                    "id": 11,
                    "leagueID": 1,
                    "location": "Detroit",
                    "logoURL": "https://a.espncdn.com/i/teamlogos/mlb/500/det.png",
                    "name": "Tigers",
                    "score": 7,
                },
                "homeTeam": {
                    "abbreviation": "HOU",
                    "apiID": 18,
                    "errors": 2,
                    "hits": 9,
                    "id": 12,
                    "leagueID": 1,
                    "location": "Houston",
                    "logoURL": "https://a.espncdn.com/i/teamlogos/mlb/500/hou.png",
                    "name": "Astros",
                    "score": 4,
                },
                "id": 1,
                "pick": None,
                "startTime": "2025-04-30T11:10:00-07:00",
                "status": "Final",
                "statusDetail": "Final",
                "subseasonID": 1,
                "winTeamID": 11,
            },
            {
                "apiID": 401695363,
                "awayTeam": {
                    "abbreviation": "ATL",
                    "apiID": 15,
                    "errors": 0,
                    "hits": 3,
                    "id": 3,
                    "leagueID": 1,
                    "location": "Atlanta",
                    "logoURL": "https://a.espncdn.com/i/teamlogos/mlb/500/atl.png",
                    "name": "Braves",
                    "score": 1,
                },
                "homeTeam": {
                    "abbreviation": "COL",
                    "apiID": 27,
                    "errors": 0,
                    "hits": 5,
                    "id": 10,
                    "leagueID": 1,
                    "location": "Colorado",
                    "logoURL": "https://a.espncdn.com/i/teamlogos/mlb/500/col.png",
                    "name": "Rockies",
                    "score": 2,
                },
                "id": 2,
                "pick": None,
                "startTime": "2025-04-30T12:10:00-07:00",
                "status": "Final",
                "statusDetail": "Final",
                "subseasonID": 1,
                "winTeamID": 10,
            },
            {
                "apiID": 401695365,
                "awayTeam": {
                    "abbreviation": "MIA",
                    "apiID": 28,
                    "errors": 1,
                    "hits": 9,
                    "id": 16,
                    "leagueID": 1,
                    "location": "Miami",
                    "logoURL": "https://a.espncdn.com/i/teamlogos/mlb/500/mia.png",
                    "name": "Marlins",
                    "score": 7,
                },
                "homeTeam": {
                    "abbreviation": "LAD",
                    "apiID": 19,
                    "errors": 0,
                    "hits": 17,
                    "id": 15,
                    "leagueID": 1,
                    "location": "Los Angeles",
                    "logoURL": "https://a.espncdn.com/i/teamlogos/mlb/500/lad.png",
                    "name": "Dodgers",
                    "score": 12,
                },
                "id": 3,
                "pick": None,
                "startTime": "2025-04-30T12:10:00-07:00",
                "status": "Final",
                "statusDetail": "Final",
                "subseasonID": 1,
                "winTeamID": 15,
            },
            {
                "apiID": 401695366,
                "awayTeam": {
                    "abbreviation": "SF",
                    "apiID": 26,
                    "errors": "-",
                    "hits": "-",
                    "id": 24,
                    "leagueID": 1,
                    "location": "San Francisco",
                    "logoURL": "https://a.espncdn.com/i/teamlogos/mlb/500/sf.png",
                    "name": "Giants",
                    "score": "-",
                },
                "homeTeam": {
                    "abbreviation": "SD",
                    "apiID": 25,
                    "errors": "-",
                    "hits": "-",
                    "id": 23,
                    "leagueID": 1,
                    "location": "San Diego",
                    "logoURL": "https://a.espncdn.com/i/teamlogos/mlb/500/sd.png",
                    "name": "Padres",
                    "score": "-",
                },
                "id": 5,
                "pick": None,
                "startTime": "2025-04-30T13:10:00-07:00",
                "status": "Postponed",
                "statusDetail": "Postponed",
                "subseasonID": 1,
                "winTeamID": None,
            },
            {
                "apiID": 401695364,
                "awayTeam": {
                    "abbreviation": "LAA",
                    "apiID": 3,
                    "errors": 2,
                    "hits": 10,
                    "id": 14,
                    "leagueID": 1,
                    "location": "Los Angeles",
                    "logoURL": "https://a.espncdn.com/i/teamlogos/mlb/500/laa.png",
                    "name": "Angels",
                    "score": 3,
                },
                "homeTeam": {
                    "abbreviation": "SEA",
                    "apiID": 12,
                    "errors": 1,
                    "hits": 12,
                    "id": 25,
                    "leagueID": 1,
                    "location": "Seattle",
                    "logoURL": "https://a.espncdn.com/i/teamlogos/mlb/500/sea.png",
                    "name": "Mariners",
                    "score": 9,
                },
                "id": 4,
                "pick": {
                    "correct": True,
                    "gameID": self.mario_pick_game_id,
                    "id": self.mario_pick_id,
                    "teamID": 25,
                    "userID": self.mario_id,
                },
                "startTime": "2025-04-30T13:10:00-07:00",
                "status": "Final",
                "statusDetail": "Final",
                "subseasonID": 1,
                "winTeamID": 25,
            },
            {
                "apiID": 401695356,
                "awayTeam": {
                    "abbreviation": "MIN",
                    "apiID": 9,
                    "errors": 1,
                    "hits": 3,
                    "id": 18,
                    "leagueID": 1,
                    "location": "Minnesota",
                    "logoURL": "https://a.espncdn.com/i/teamlogos/mlb/500/min.png",
                    "name": "Twins",
                    "score": 0,
                },
                "homeTeam": {
                    "abbreviation": "CLE",
                    "apiID": 5,
                    "errors": 1,
                    "hits": 4,
                    "id": 9,
                    "leagueID": 1,
                    "location": "Cleveland",
                    "logoURL": "https://a.espncdn.com/i/teamlogos/mlb/500/cle.png",
                    "name": "Guardians",
                    "score": 1,
                },
                "id": 6,
                "pick": None,
                "startTime": "2025-04-30T15:10:00-07:00",
                "status": "Bot 7th",
                "statusDetail": "Bot 7th",
                "subseasonID": 1,
                "winTeamID": None,
            },
            {
                "apiID": 401695357,
                "awayTeam": {
                    "abbreviation": "NYY",
                    "apiID": 10,
                    "errors": 0,
                    "hits": 3,
                    "id": 20,
                    "leagueID": 1,
                    "location": "New York",
                    "logoURL": "https://a.espncdn.com/i/teamlogos/mlb/500/nyy.png",
                    "name": "Yankees",
                    "score": 3,
                },
                "homeTeam": {
                    "abbreviation": "BAL",
                    "apiID": 1,
                    "errors": 0,
                    "hits": 8,
                    "id": 4,
                    "leagueID": 1,
                    "location": "Baltimore",
                    "logoURL": "https://a.espncdn.com/i/teamlogos/mlb/500/bal.png",
                    "name": "Orioles",
                    "score": 4,
                },
                "id": 7,
                "pick": None,
                "startTime": "2025-04-30T15:35:00-07:00",
                "status": "Top 5th",
                "statusDetail": "Top 5th",
                "subseasonID": 1,
                "winTeamID": None,
            },
            {
                "apiID": 401695358,
                "awayTeam": {
                    "abbreviation": "STL",
                    "apiID": 24,
                    "errors": 0,
                    "hits": 8,
                    "id": 26,
                    "leagueID": 1,
                    "location": "St. Louis",
                    "logoURL": "https://a.espncdn.com/i/teamlogos/mlb/500/stl.png",
                    "name": "Cardinals",
                    "score": 9,
                },
                "homeTeam": {
                    "abbreviation": "CIN",
                    "apiID": 17,
                    "errors": 0,
                    "hits": 4,
                    "id": 8,
                    "leagueID": 1,
                    "location": "Cincinnati",
                    "logoURL": "https://a.espncdn.com/i/teamlogos/mlb/500/cin.png",
                    "name": "Reds",
                    "score": 0,
                },
                "id": 9,
                "pick": None,
                "startTime": "2025-04-30T15:40:00-07:00",
                "status": "Bot 4th",
                "statusDetail": "Bot 4th",
                "subseasonID": 1,
                "winTeamID": None,
            },
            {
                "apiID": 401695354,
                "awayTeam": {
                    "abbreviation": "CHC",
                    "apiID": 16,
                    "errors": 0,
                    "hits": 6,
                    "id": 6,
                    "leagueID": 1,
                    "location": "Chicago",
                    "logoURL": "https://a.espncdn.com/i/teamlogos/mlb/500/chc.png",
                    "name": "Cubs",
                    "score": 0,
                },
                "homeTeam": {
                    "abbreviation": "PIT",
                    "apiID": 23,
                    "errors": 0,
                    "hits": 5,
                    "id": 22,
                    "leagueID": 1,
                    "location": "Pittsburgh",
                    "logoURL": "https://a.espncdn.com/i/teamlogos/mlb/500/pit.png",
                    "name": "Pirates",
                    "score": 2,
                },
                "id": 8,
                "pick": None,
                "startTime": "2025-04-30T15:40:00-07:00",
                "status": "Top 5th",
                "statusDetail": "Top 5th",
                "subseasonID": 1,
                "winTeamID": None,
            },
            {
                "apiID": 401695359,
                "awayTeam": {
                    "abbreviation": "WSH",
                    "apiID": 20,
                    "errors": 0,
                    "hits": 5,
                    "id": 30,
                    "leagueID": 1,
                    "location": "Washington",
                    "logoURL": "https://a.espncdn.com/i/teamlogos/mlb/500/wsh.png",
                    "name": "Nationals",
                    "score": 1,
                },
                "homeTeam": {
                    "abbreviation": "PHI",
                    "apiID": 22,
                    "errors": 0,
                    "hits": 5,
                    "id": 21,
                    "leagueID": 1,
                    "location": "Philadelphia",
                    "logoURL": "https://a.espncdn.com/i/teamlogos/mlb/500/phi.png",
                    "name": "Phillies",
                    "score": 4,
                },
                "id": 10,
                "pick": None,
                "startTime": "2025-04-30T15:45:00-07:00",
                "status": "Top 5th",
                "statusDetail": "Top 5th",
                "subseasonID": 1,
                "winTeamID": None,
            },
            {
                "apiID": 401695355,
                "awayTeam": {
                    "abbreviation": "KC",
                    "apiID": 7,
                    "errors": 0,
                    "hits": 4,
                    "id": 13,
                    "leagueID": 1,
                    "location": "Kansas City",
                    "logoURL": "https://a.espncdn.com/i/teamlogos/mlb/500/kc.png",
                    "name": "Royals",
                    "score": 2,
                },
                "homeTeam": {
                    "abbreviation": "TB",
                    "apiID": 30,
                    "errors": 0,
                    "hits": 0,
                    "id": 27,
                    "leagueID": 1,
                    "location": "Tampa Bay",
                    "logoURL": "https://a.espncdn.com/i/teamlogos/mlb/500/tb.png",
                    "name": "Rays",
                    "score": 0,
                },
                "id": 11,
                "pick": None,
                "startTime": "2025-04-30T16:05:00-07:00",
                "status": "Top 5th",
                "statusDetail": "Top 5th",
                "subseasonID": 1,
                "winTeamID": None,
            },
            {
                "apiID": 401695353,
                "awayTeam": {
                    "abbreviation": "BOS",
                    "apiID": 2,
                    "errors": 0,
                    "hits": 4,
                    "id": 5,
                    "leagueID": 1,
                    "location": "Boston",
                    "logoURL": "https://a.espncdn.com/i/teamlogos/mlb/500/bos.png",
                    "name": "Red Sox",
                    "score": 4,
                },
                "homeTeam": {
                    "abbreviation": "TOR",
                    "apiID": 14,
                    "errors": 1,
                    "hits": 1,
                    "id": 29,
                    "leagueID": 1,
                    "location": "Toronto",
                    "logoURL": "https://a.espncdn.com/i/teamlogos/mlb/500/tor.png",
                    "name": "Blue Jays",
                    "score": 0,
                },
                "id": 12,
                "pick": None,
                "startTime": "2025-04-30T16:07:00-07:00",
                "status": "End 2nd",
                "statusDetail": "End 2nd",
                "subseasonID": 1,
                "winTeamID": None,
            },
            {
                "apiID": 401695352,
                "awayTeam": {
                    "abbreviation": "ARI",
                    "apiID": 29,
                    "errors": 0,
                    "hits": 1,
                    "id": 1,
                    "leagueID": 1,
                    "location": "Arizona",
                    "logoURL": "https://a.espncdn.com/i/teamlogos/mlb/500/ari.png",
                    "name": "Diamondbacks",
                    "score": 0,
                },
                "homeTeam": {
                    "abbreviation": "NYM",
                    "apiID": 21,
                    "errors": 0,
                    "hits": 2,
                    "id": 19,
                    "leagueID": 1,
                    "location": "New York",
                    "logoURL": "https://a.espncdn.com/i/teamlogos/mlb/500/nym.png",
                    "name": "Mets",
                    "score": 0,
                },
                "id": 13,
                "pick": None,
                "startTime": "2025-04-30T16:10:00-07:00",
                "status": "Bot 3rd",
                "statusDetail": "Bot 3rd",
                "subseasonID": 1,
                "winTeamID": None,
            },
            {
                "apiID": 401695361,
                "awayTeam": {
                    "abbreviation": "MIL",
                    "apiID": 8,
                    "errors": 0,
                    "hits": 3,
                    "id": 17,
                    "leagueID": 1,
                    "location": "Milwaukee",
                    "logoURL": "https://a.espncdn.com/i/teamlogos/mlb/500/mil.png",
                    "name": "Brewers",
                    "score": 2,
                },
                "homeTeam": {
                    "abbreviation": "CHW",
                    "apiID": 4,
                    "errors": 1,
                    "hits": 0,
                    "id": 7,
                    "leagueID": 1,
                    "location": "Chicago",
                    "logoURL": "https://a.espncdn.com/i/teamlogos/mlb/500/chw.png",
                    "name": "White Sox",
                    "score": 0,
                },
                "id": 14,
                "pick": None,
                "startTime": "2025-04-30T16:40:00-07:00",
                "status": "Bot 1st",
                "statusDetail": "Bot 1st",
                "subseasonID": 1,
                "winTeamID": None,
            },
            {
                "apiID": 401695362,
                "awayTeam": {
                    "abbreviation": "ATH",
                    "apiID": 11,
                    "errors": "-",
                    "hits": "-",
                    "id": 2,
                    "leagueID": 1,
                    "location": "",
                    "logoURL": "https://a.espncdn.com/i/teamlogos/mlb/500/ath.png",
                    "name": "Athletics",
                    "score": "-",
                },
                "homeTeam": {
                    "abbreviation": "TEX",
                    "apiID": 13,
                    "errors": "-",
                    "hits": "-",
                    "id": 28,
                    "leagueID": 1,
                    "location": "Texas",
                    "logoURL": "https://a.espncdn.com/i/teamlogos/mlb/500/tex.png",
                    "name": "Rangers",
                    "score": "-",
                },
                "id": 15,
                "pick": None,
                "startTime": "2025-04-30T17:05:00-07:00",
                "status": "Scheduled",
                "statusDetail": "4/30 - 8:05 PM EDT",
                "subseasonID": 1,
                "winTeamID": None,
            }
        ]
    }
